name: Java CI with Maven

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw --batch-mode --update-snapshots install -DskipTests

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 18 ]
        container: [ 'WILDFLY_MANAGED', 'WILDFLY_REMOTE' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw --batch-mode --update-snapshots -P ${{ matrix.container }} install