name: Java CI with Maven

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw --batch-mode --update-snapshots install -DskipTests

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [ 'WILDFLY_MANAGED_8', 'GLASSFISH_MANAGED_4.0' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw --batch-mode --update-snapshots -P ${{ matrix.container }} install